// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CloudHostsColumns holds the columns for the "cloud_hosts" table.
	CloudHostsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "uuid", Type: field.TypeString, Unique: true},
		{Name: "state", Type: field.TypeString, Default: "RUNNING"},
		{Name: "ipv6address_private", Type: field.TypeString},
		{Name: "ipv6address_public", Type: field.TypeString},
		{Name: "ipv4address_private", Type: field.TypeString},
		{Name: "ipv4address_public", Type: field.TypeString},
		{Name: "memory", Type: field.TypeInt},
		{Name: "cpu", Type: field.TypeInt},
		{Name: "created_time", Type: field.TypeTime},
		{Name: "expired_time", Type: field.TypeTime},
		{Name: "instance_name", Type: field.TypeString},
		{Name: "image_name", Type: field.TypeString},
		{Name: "os_type", Type: field.TypeString},
		{Name: "manufacturer", Type: field.TypeString},
		{Name: "zone", Type: field.TypeString},
		{Name: "security_groups", Type: field.TypeString},
		{Name: "bill_type", Type: field.TypeString},
		{Name: "charge_type", Type: field.TypeString},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "instance_type", Type: field.TypeString},
	}
	// CloudHostsTable holds the schema information for the "cloud_hosts" table.
	CloudHostsTable = &schema.Table{
		Name:       "cloud_hosts",
		Columns:    CloudHostsColumns,
		PrimaryKey: []*schema.Column{CloudHostsColumns[0]},
	}
	// ClustersColumns holds the columns for the "clusters" table.
	ClustersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "kubeconfig", Type: field.TypeString, Default: "unknown"},
	}
	// ClustersTable holds the schema information for the "clusters" table.
	ClustersTable = &schema.Table{
		Name:       "clusters",
		Columns:    ClustersColumns,
		PrimaryKey: []*schema.Column{ClustersColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "age", Type: field.TypeInt},
		{Name: "name", Type: field.TypeString, Default: "unknown"},
		{Name: "password", Type: field.TypeString, Default: "123456"},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CloudHostsTable,
		ClustersTable,
		UsersTable,
	}
)

func init() {
}
