// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"kubecit/ent/cloudhost"
	"kubecit/ent/predicate"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CloudHostQuery is the builder for querying CloudHost entities.
type CloudHostQuery struct {
	config
	ctx        *QueryContext
	order      []cloudhost.OrderOption
	inters     []Interceptor
	predicates []predicate.CloudHost
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CloudHostQuery builder.
func (chq *CloudHostQuery) Where(ps ...predicate.CloudHost) *CloudHostQuery {
	chq.predicates = append(chq.predicates, ps...)
	return chq
}

// Limit the number of records to be returned by this query.
func (chq *CloudHostQuery) Limit(limit int) *CloudHostQuery {
	chq.ctx.Limit = &limit
	return chq
}

// Offset to start from.
func (chq *CloudHostQuery) Offset(offset int) *CloudHostQuery {
	chq.ctx.Offset = &offset
	return chq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (chq *CloudHostQuery) Unique(unique bool) *CloudHostQuery {
	chq.ctx.Unique = &unique
	return chq
}

// Order specifies how the records should be ordered.
func (chq *CloudHostQuery) Order(o ...cloudhost.OrderOption) *CloudHostQuery {
	chq.order = append(chq.order, o...)
	return chq
}

// First returns the first CloudHost entity from the query.
// Returns a *NotFoundError when no CloudHost was found.
func (chq *CloudHostQuery) First(ctx context.Context) (*CloudHost, error) {
	nodes, err := chq.Limit(1).All(setContextOp(ctx, chq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{cloudhost.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (chq *CloudHostQuery) FirstX(ctx context.Context) *CloudHost {
	node, err := chq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first CloudHost ID from the query.
// Returns a *NotFoundError when no CloudHost ID was found.
func (chq *CloudHostQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = chq.Limit(1).IDs(setContextOp(ctx, chq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{cloudhost.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (chq *CloudHostQuery) FirstIDX(ctx context.Context) int {
	id, err := chq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single CloudHost entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one CloudHost entity is found.
// Returns a *NotFoundError when no CloudHost entities are found.
func (chq *CloudHostQuery) Only(ctx context.Context) (*CloudHost, error) {
	nodes, err := chq.Limit(2).All(setContextOp(ctx, chq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{cloudhost.Label}
	default:
		return nil, &NotSingularError{cloudhost.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (chq *CloudHostQuery) OnlyX(ctx context.Context) *CloudHost {
	node, err := chq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only CloudHost ID in the query.
// Returns a *NotSingularError when more than one CloudHost ID is found.
// Returns a *NotFoundError when no entities are found.
func (chq *CloudHostQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = chq.Limit(2).IDs(setContextOp(ctx, chq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{cloudhost.Label}
	default:
		err = &NotSingularError{cloudhost.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (chq *CloudHostQuery) OnlyIDX(ctx context.Context) int {
	id, err := chq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of CloudHosts.
func (chq *CloudHostQuery) All(ctx context.Context) ([]*CloudHost, error) {
	ctx = setContextOp(ctx, chq.ctx, "All")
	if err := chq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*CloudHost, *CloudHostQuery]()
	return withInterceptors[[]*CloudHost](ctx, chq, qr, chq.inters)
}

// AllX is like All, but panics if an error occurs.
func (chq *CloudHostQuery) AllX(ctx context.Context) []*CloudHost {
	nodes, err := chq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of CloudHost IDs.
func (chq *CloudHostQuery) IDs(ctx context.Context) (ids []int, err error) {
	if chq.ctx.Unique == nil && chq.path != nil {
		chq.Unique(true)
	}
	ctx = setContextOp(ctx, chq.ctx, "IDs")
	if err = chq.Select(cloudhost.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (chq *CloudHostQuery) IDsX(ctx context.Context) []int {
	ids, err := chq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (chq *CloudHostQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, chq.ctx, "Count")
	if err := chq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, chq, querierCount[*CloudHostQuery](), chq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (chq *CloudHostQuery) CountX(ctx context.Context) int {
	count, err := chq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (chq *CloudHostQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, chq.ctx, "Exist")
	switch _, err := chq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (chq *CloudHostQuery) ExistX(ctx context.Context) bool {
	exist, err := chq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CloudHostQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (chq *CloudHostQuery) Clone() *CloudHostQuery {
	if chq == nil {
		return nil
	}
	return &CloudHostQuery{
		config:     chq.config,
		ctx:        chq.ctx.Clone(),
		order:      append([]cloudhost.OrderOption{}, chq.order...),
		inters:     append([]Interceptor{}, chq.inters...),
		predicates: append([]predicate.CloudHost{}, chq.predicates...),
		// clone intermediate query.
		sql:  chq.sql.Clone(),
		path: chq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		InstanceId string `json:"instanceId,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.CloudHost.Query().
//		GroupBy(cloudhost.FieldInstanceId).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (chq *CloudHostQuery) GroupBy(field string, fields ...string) *CloudHostGroupBy {
	chq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CloudHostGroupBy{build: chq}
	grbuild.flds = &chq.ctx.Fields
	grbuild.label = cloudhost.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		InstanceId string `json:"instanceId,omitempty"`
//	}
//
//	client.CloudHost.Query().
//		Select(cloudhost.FieldInstanceId).
//		Scan(ctx, &v)
func (chq *CloudHostQuery) Select(fields ...string) *CloudHostSelect {
	chq.ctx.Fields = append(chq.ctx.Fields, fields...)
	sbuild := &CloudHostSelect{CloudHostQuery: chq}
	sbuild.label = cloudhost.Label
	sbuild.flds, sbuild.scan = &chq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CloudHostSelect configured with the given aggregations.
func (chq *CloudHostQuery) Aggregate(fns ...AggregateFunc) *CloudHostSelect {
	return chq.Select().Aggregate(fns...)
}

func (chq *CloudHostQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range chq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, chq); err != nil {
				return err
			}
		}
	}
	for _, f := range chq.ctx.Fields {
		if !cloudhost.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if chq.path != nil {
		prev, err := chq.path(ctx)
		if err != nil {
			return err
		}
		chq.sql = prev
	}
	return nil
}

func (chq *CloudHostQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*CloudHost, error) {
	var (
		nodes = []*CloudHost{}
		_spec = chq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*CloudHost).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &CloudHost{config: chq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, chq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (chq *CloudHostQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := chq.querySpec()
	_spec.Node.Columns = chq.ctx.Fields
	if len(chq.ctx.Fields) > 0 {
		_spec.Unique = chq.ctx.Unique != nil && *chq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, chq.driver, _spec)
}

func (chq *CloudHostQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(cloudhost.Table, cloudhost.Columns, sqlgraph.NewFieldSpec(cloudhost.FieldID, field.TypeInt))
	_spec.From = chq.sql
	if unique := chq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if chq.path != nil {
		_spec.Unique = true
	}
	if fields := chq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, cloudhost.FieldID)
		for i := range fields {
			if fields[i] != cloudhost.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := chq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := chq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := chq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := chq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (chq *CloudHostQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(chq.driver.Dialect())
	t1 := builder.Table(cloudhost.Table)
	columns := chq.ctx.Fields
	if len(columns) == 0 {
		columns = cloudhost.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if chq.sql != nil {
		selector = chq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if chq.ctx.Unique != nil && *chq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range chq.predicates {
		p(selector)
	}
	for _, p := range chq.order {
		p(selector)
	}
	if offset := chq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := chq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// CloudHostGroupBy is the group-by builder for CloudHost entities.
type CloudHostGroupBy struct {
	selector
	build *CloudHostQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (chgb *CloudHostGroupBy) Aggregate(fns ...AggregateFunc) *CloudHostGroupBy {
	chgb.fns = append(chgb.fns, fns...)
	return chgb
}

// Scan applies the selector query and scans the result into the given value.
func (chgb *CloudHostGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, chgb.build.ctx, "GroupBy")
	if err := chgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CloudHostQuery, *CloudHostGroupBy](ctx, chgb.build, chgb, chgb.build.inters, v)
}

func (chgb *CloudHostGroupBy) sqlScan(ctx context.Context, root *CloudHostQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(chgb.fns))
	for _, fn := range chgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*chgb.flds)+len(chgb.fns))
		for _, f := range *chgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*chgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := chgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CloudHostSelect is the builder for selecting fields of CloudHost entities.
type CloudHostSelect struct {
	*CloudHostQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (chs *CloudHostSelect) Aggregate(fns ...AggregateFunc) *CloudHostSelect {
	chs.fns = append(chs.fns, fns...)
	return chs
}

// Scan applies the selector query and scans the result into the given value.
func (chs *CloudHostSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, chs.ctx, "Select")
	if err := chs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CloudHostQuery, *CloudHostSelect](ctx, chs.CloudHostQuery, chs, chs.inters, v)
}

func (chs *CloudHostSelect) sqlScan(ctx context.Context, root *CloudHostQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(chs.fns))
	for _, fn := range chs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*chs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := chs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
