// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"kubecit/ent/cloudhost"
	"kubecit/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CloudHostUpdate is the builder for updating CloudHost entities.
type CloudHostUpdate struct {
	config
	hooks    []Hook
	mutation *CloudHostMutation
}

// Where appends a list predicates to the CloudHostUpdate builder.
func (chu *CloudHostUpdate) Where(ps ...predicate.CloudHost) *CloudHostUpdate {
	chu.mutation.Where(ps...)
	return chu
}

// SetInstanceId sets the "instanceId" field.
func (chu *CloudHostUpdate) SetInstanceId(s string) *CloudHostUpdate {
	chu.mutation.SetInstanceId(s)
	return chu
}

// SetVpcId sets the "vpcId" field.
func (chu *CloudHostUpdate) SetVpcId(s string) *CloudHostUpdate {
	chu.mutation.SetVpcId(s)
	return chu
}

// SetSubnetId sets the "subnetId" field.
func (chu *CloudHostUpdate) SetSubnetId(s string) *CloudHostUpdate {
	chu.mutation.SetSubnetId(s)
	return chu
}

// SetInstanceName sets the "instanceName" field.
func (chu *CloudHostUpdate) SetInstanceName(s string) *CloudHostUpdate {
	chu.mutation.SetInstanceName(s)
	return chu
}

// SetInstanceState sets the "instanceState" field.
func (chu *CloudHostUpdate) SetInstanceState(s string) *CloudHostUpdate {
	chu.mutation.SetInstanceState(s)
	return chu
}

// SetCPU sets the "cpu" field.
func (chu *CloudHostUpdate) SetCPU(i int64) *CloudHostUpdate {
	chu.mutation.ResetCPU()
	chu.mutation.SetCPU(i)
	return chu
}

// AddCPU adds i to the "cpu" field.
func (chu *CloudHostUpdate) AddCPU(i int64) *CloudHostUpdate {
	chu.mutation.AddCPU(i)
	return chu
}

// SetMemory sets the "memory" field.
func (chu *CloudHostUpdate) SetMemory(i int64) *CloudHostUpdate {
	chu.mutation.ResetMemory()
	chu.mutation.SetMemory(i)
	return chu
}

// AddMemory adds i to the "memory" field.
func (chu *CloudHostUpdate) AddMemory(i int64) *CloudHostUpdate {
	chu.mutation.AddMemory(i)
	return chu
}

// SetCreatedTime sets the "createdTime" field.
func (chu *CloudHostUpdate) SetCreatedTime(s string) *CloudHostUpdate {
	chu.mutation.SetCreatedTime(s)
	return chu
}

// SetInstanceType sets the "instanceType" field.
func (chu *CloudHostUpdate) SetInstanceType(s string) *CloudHostUpdate {
	chu.mutation.SetInstanceType(s)
	return chu
}

// SetEniLimit sets the "eniLimit" field.
func (chu *CloudHostUpdate) SetEniLimit(i int64) *CloudHostUpdate {
	chu.mutation.ResetEniLimit()
	chu.mutation.SetEniLimit(i)
	return chu
}

// AddEniLimit adds i to the "eniLimit" field.
func (chu *CloudHostUpdate) AddEniLimit(i int64) *CloudHostUpdate {
	chu.mutation.AddEniLimit(i)
	return chu
}

// SetEnilpLimit sets the "enilpLimit" field.
func (chu *CloudHostUpdate) SetEnilpLimit(i int64) *CloudHostUpdate {
	chu.mutation.ResetEnilpLimit()
	chu.mutation.SetEnilpLimit(i)
	return chu
}

// AddEnilpLimit adds i to the "enilpLimit" field.
func (chu *CloudHostUpdate) AddEnilpLimit(i int64) *CloudHostUpdate {
	chu.mutation.AddEnilpLimit(i)
	return chu
}

// SetInstanceEniCount sets the "instanceEniCount" field.
func (chu *CloudHostUpdate) SetInstanceEniCount(i int64) *CloudHostUpdate {
	chu.mutation.ResetInstanceEniCount()
	chu.mutation.SetInstanceEniCount(i)
	return chu
}

// AddInstanceEniCount adds i to the "instanceEniCount" field.
func (chu *CloudHostUpdate) AddInstanceEniCount(i int64) *CloudHostUpdate {
	chu.mutation.AddInstanceEniCount(i)
	return chu
}

// Mutation returns the CloudHostMutation object of the builder.
func (chu *CloudHostUpdate) Mutation() *CloudHostMutation {
	return chu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (chu *CloudHostUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, chu.sqlSave, chu.mutation, chu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (chu *CloudHostUpdate) SaveX(ctx context.Context) int {
	affected, err := chu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (chu *CloudHostUpdate) Exec(ctx context.Context) error {
	_, err := chu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (chu *CloudHostUpdate) ExecX(ctx context.Context) {
	if err := chu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (chu *CloudHostUpdate) check() error {
	if v, ok := chu.mutation.InstanceId(); ok {
		if err := cloudhost.InstanceIdValidator(v); err != nil {
			return &ValidationError{Name: "instanceId", err: fmt.Errorf(`ent: validator failed for field "CloudHost.instanceId": %w`, err)}
		}
	}
	if v, ok := chu.mutation.VpcId(); ok {
		if err := cloudhost.VpcIdValidator(v); err != nil {
			return &ValidationError{Name: "vpcId", err: fmt.Errorf(`ent: validator failed for field "CloudHost.vpcId": %w`, err)}
		}
	}
	return nil
}

func (chu *CloudHostUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := chu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(cloudhost.Table, cloudhost.Columns, sqlgraph.NewFieldSpec(cloudhost.FieldID, field.TypeInt))
	if ps := chu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := chu.mutation.InstanceId(); ok {
		_spec.SetField(cloudhost.FieldInstanceId, field.TypeString, value)
	}
	if value, ok := chu.mutation.VpcId(); ok {
		_spec.SetField(cloudhost.FieldVpcId, field.TypeString, value)
	}
	if value, ok := chu.mutation.SubnetId(); ok {
		_spec.SetField(cloudhost.FieldSubnetId, field.TypeString, value)
	}
	if value, ok := chu.mutation.InstanceName(); ok {
		_spec.SetField(cloudhost.FieldInstanceName, field.TypeString, value)
	}
	if value, ok := chu.mutation.InstanceState(); ok {
		_spec.SetField(cloudhost.FieldInstanceState, field.TypeString, value)
	}
	if value, ok := chu.mutation.CPU(); ok {
		_spec.SetField(cloudhost.FieldCPU, field.TypeInt64, value)
	}
	if value, ok := chu.mutation.AddedCPU(); ok {
		_spec.AddField(cloudhost.FieldCPU, field.TypeInt64, value)
	}
	if value, ok := chu.mutation.Memory(); ok {
		_spec.SetField(cloudhost.FieldMemory, field.TypeInt64, value)
	}
	if value, ok := chu.mutation.AddedMemory(); ok {
		_spec.AddField(cloudhost.FieldMemory, field.TypeInt64, value)
	}
	if value, ok := chu.mutation.CreatedTime(); ok {
		_spec.SetField(cloudhost.FieldCreatedTime, field.TypeString, value)
	}
	if value, ok := chu.mutation.InstanceType(); ok {
		_spec.SetField(cloudhost.FieldInstanceType, field.TypeString, value)
	}
	if value, ok := chu.mutation.EniLimit(); ok {
		_spec.SetField(cloudhost.FieldEniLimit, field.TypeInt64, value)
	}
	if value, ok := chu.mutation.AddedEniLimit(); ok {
		_spec.AddField(cloudhost.FieldEniLimit, field.TypeInt64, value)
	}
	if value, ok := chu.mutation.EnilpLimit(); ok {
		_spec.SetField(cloudhost.FieldEnilpLimit, field.TypeInt64, value)
	}
	if value, ok := chu.mutation.AddedEnilpLimit(); ok {
		_spec.AddField(cloudhost.FieldEnilpLimit, field.TypeInt64, value)
	}
	if value, ok := chu.mutation.InstanceEniCount(); ok {
		_spec.SetField(cloudhost.FieldInstanceEniCount, field.TypeInt64, value)
	}
	if value, ok := chu.mutation.AddedInstanceEniCount(); ok {
		_spec.AddField(cloudhost.FieldInstanceEniCount, field.TypeInt64, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, chu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{cloudhost.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	chu.mutation.done = true
	return n, nil
}

// CloudHostUpdateOne is the builder for updating a single CloudHost entity.
type CloudHostUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CloudHostMutation
}

// SetInstanceId sets the "instanceId" field.
func (chuo *CloudHostUpdateOne) SetInstanceId(s string) *CloudHostUpdateOne {
	chuo.mutation.SetInstanceId(s)
	return chuo
}

// SetVpcId sets the "vpcId" field.
func (chuo *CloudHostUpdateOne) SetVpcId(s string) *CloudHostUpdateOne {
	chuo.mutation.SetVpcId(s)
	return chuo
}

// SetSubnetId sets the "subnetId" field.
func (chuo *CloudHostUpdateOne) SetSubnetId(s string) *CloudHostUpdateOne {
	chuo.mutation.SetSubnetId(s)
	return chuo
}

// SetInstanceName sets the "instanceName" field.
func (chuo *CloudHostUpdateOne) SetInstanceName(s string) *CloudHostUpdateOne {
	chuo.mutation.SetInstanceName(s)
	return chuo
}

// SetInstanceState sets the "instanceState" field.
func (chuo *CloudHostUpdateOne) SetInstanceState(s string) *CloudHostUpdateOne {
	chuo.mutation.SetInstanceState(s)
	return chuo
}

// SetCPU sets the "cpu" field.
func (chuo *CloudHostUpdateOne) SetCPU(i int64) *CloudHostUpdateOne {
	chuo.mutation.ResetCPU()
	chuo.mutation.SetCPU(i)
	return chuo
}

// AddCPU adds i to the "cpu" field.
func (chuo *CloudHostUpdateOne) AddCPU(i int64) *CloudHostUpdateOne {
	chuo.mutation.AddCPU(i)
	return chuo
}

// SetMemory sets the "memory" field.
func (chuo *CloudHostUpdateOne) SetMemory(i int64) *CloudHostUpdateOne {
	chuo.mutation.ResetMemory()
	chuo.mutation.SetMemory(i)
	return chuo
}

// AddMemory adds i to the "memory" field.
func (chuo *CloudHostUpdateOne) AddMemory(i int64) *CloudHostUpdateOne {
	chuo.mutation.AddMemory(i)
	return chuo
}

// SetCreatedTime sets the "createdTime" field.
func (chuo *CloudHostUpdateOne) SetCreatedTime(s string) *CloudHostUpdateOne {
	chuo.mutation.SetCreatedTime(s)
	return chuo
}

// SetInstanceType sets the "instanceType" field.
func (chuo *CloudHostUpdateOne) SetInstanceType(s string) *CloudHostUpdateOne {
	chuo.mutation.SetInstanceType(s)
	return chuo
}

// SetEniLimit sets the "eniLimit" field.
func (chuo *CloudHostUpdateOne) SetEniLimit(i int64) *CloudHostUpdateOne {
	chuo.mutation.ResetEniLimit()
	chuo.mutation.SetEniLimit(i)
	return chuo
}

// AddEniLimit adds i to the "eniLimit" field.
func (chuo *CloudHostUpdateOne) AddEniLimit(i int64) *CloudHostUpdateOne {
	chuo.mutation.AddEniLimit(i)
	return chuo
}

// SetEnilpLimit sets the "enilpLimit" field.
func (chuo *CloudHostUpdateOne) SetEnilpLimit(i int64) *CloudHostUpdateOne {
	chuo.mutation.ResetEnilpLimit()
	chuo.mutation.SetEnilpLimit(i)
	return chuo
}

// AddEnilpLimit adds i to the "enilpLimit" field.
func (chuo *CloudHostUpdateOne) AddEnilpLimit(i int64) *CloudHostUpdateOne {
	chuo.mutation.AddEnilpLimit(i)
	return chuo
}

// SetInstanceEniCount sets the "instanceEniCount" field.
func (chuo *CloudHostUpdateOne) SetInstanceEniCount(i int64) *CloudHostUpdateOne {
	chuo.mutation.ResetInstanceEniCount()
	chuo.mutation.SetInstanceEniCount(i)
	return chuo
}

// AddInstanceEniCount adds i to the "instanceEniCount" field.
func (chuo *CloudHostUpdateOne) AddInstanceEniCount(i int64) *CloudHostUpdateOne {
	chuo.mutation.AddInstanceEniCount(i)
	return chuo
}

// Mutation returns the CloudHostMutation object of the builder.
func (chuo *CloudHostUpdateOne) Mutation() *CloudHostMutation {
	return chuo.mutation
}

// Where appends a list predicates to the CloudHostUpdate builder.
func (chuo *CloudHostUpdateOne) Where(ps ...predicate.CloudHost) *CloudHostUpdateOne {
	chuo.mutation.Where(ps...)
	return chuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (chuo *CloudHostUpdateOne) Select(field string, fields ...string) *CloudHostUpdateOne {
	chuo.fields = append([]string{field}, fields...)
	return chuo
}

// Save executes the query and returns the updated CloudHost entity.
func (chuo *CloudHostUpdateOne) Save(ctx context.Context) (*CloudHost, error) {
	return withHooks(ctx, chuo.sqlSave, chuo.mutation, chuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (chuo *CloudHostUpdateOne) SaveX(ctx context.Context) *CloudHost {
	node, err := chuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (chuo *CloudHostUpdateOne) Exec(ctx context.Context) error {
	_, err := chuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (chuo *CloudHostUpdateOne) ExecX(ctx context.Context) {
	if err := chuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (chuo *CloudHostUpdateOne) check() error {
	if v, ok := chuo.mutation.InstanceId(); ok {
		if err := cloudhost.InstanceIdValidator(v); err != nil {
			return &ValidationError{Name: "instanceId", err: fmt.Errorf(`ent: validator failed for field "CloudHost.instanceId": %w`, err)}
		}
	}
	if v, ok := chuo.mutation.VpcId(); ok {
		if err := cloudhost.VpcIdValidator(v); err != nil {
			return &ValidationError{Name: "vpcId", err: fmt.Errorf(`ent: validator failed for field "CloudHost.vpcId": %w`, err)}
		}
	}
	return nil
}

func (chuo *CloudHostUpdateOne) sqlSave(ctx context.Context) (_node *CloudHost, err error) {
	if err := chuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(cloudhost.Table, cloudhost.Columns, sqlgraph.NewFieldSpec(cloudhost.FieldID, field.TypeInt))
	id, ok := chuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CloudHost.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := chuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, cloudhost.FieldID)
		for _, f := range fields {
			if !cloudhost.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != cloudhost.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := chuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := chuo.mutation.InstanceId(); ok {
		_spec.SetField(cloudhost.FieldInstanceId, field.TypeString, value)
	}
	if value, ok := chuo.mutation.VpcId(); ok {
		_spec.SetField(cloudhost.FieldVpcId, field.TypeString, value)
	}
	if value, ok := chuo.mutation.SubnetId(); ok {
		_spec.SetField(cloudhost.FieldSubnetId, field.TypeString, value)
	}
	if value, ok := chuo.mutation.InstanceName(); ok {
		_spec.SetField(cloudhost.FieldInstanceName, field.TypeString, value)
	}
	if value, ok := chuo.mutation.InstanceState(); ok {
		_spec.SetField(cloudhost.FieldInstanceState, field.TypeString, value)
	}
	if value, ok := chuo.mutation.CPU(); ok {
		_spec.SetField(cloudhost.FieldCPU, field.TypeInt64, value)
	}
	if value, ok := chuo.mutation.AddedCPU(); ok {
		_spec.AddField(cloudhost.FieldCPU, field.TypeInt64, value)
	}
	if value, ok := chuo.mutation.Memory(); ok {
		_spec.SetField(cloudhost.FieldMemory, field.TypeInt64, value)
	}
	if value, ok := chuo.mutation.AddedMemory(); ok {
		_spec.AddField(cloudhost.FieldMemory, field.TypeInt64, value)
	}
	if value, ok := chuo.mutation.CreatedTime(); ok {
		_spec.SetField(cloudhost.FieldCreatedTime, field.TypeString, value)
	}
	if value, ok := chuo.mutation.InstanceType(); ok {
		_spec.SetField(cloudhost.FieldInstanceType, field.TypeString, value)
	}
	if value, ok := chuo.mutation.EniLimit(); ok {
		_spec.SetField(cloudhost.FieldEniLimit, field.TypeInt64, value)
	}
	if value, ok := chuo.mutation.AddedEniLimit(); ok {
		_spec.AddField(cloudhost.FieldEniLimit, field.TypeInt64, value)
	}
	if value, ok := chuo.mutation.EnilpLimit(); ok {
		_spec.SetField(cloudhost.FieldEnilpLimit, field.TypeInt64, value)
	}
	if value, ok := chuo.mutation.AddedEnilpLimit(); ok {
		_spec.AddField(cloudhost.FieldEnilpLimit, field.TypeInt64, value)
	}
	if value, ok := chuo.mutation.InstanceEniCount(); ok {
		_spec.SetField(cloudhost.FieldInstanceEniCount, field.TypeInt64, value)
	}
	if value, ok := chuo.mutation.AddedInstanceEniCount(); ok {
		_spec.AddField(cloudhost.FieldInstanceEniCount, field.TypeInt64, value)
	}
	_node = &CloudHost{config: chuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, chuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{cloudhost.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	chuo.mutation.done = true
	return _node, nil
}
