// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"kubecit/ent/cloudprovider"
	"kubecit/ent/predicate"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CloudProviderQuery is the builder for querying CloudProvider entities.
type CloudProviderQuery struct {
	config
	ctx        *QueryContext
	order      []cloudprovider.OrderOption
	inters     []Interceptor
	predicates []predicate.CloudProvider
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CloudProviderQuery builder.
func (cpq *CloudProviderQuery) Where(ps ...predicate.CloudProvider) *CloudProviderQuery {
	cpq.predicates = append(cpq.predicates, ps...)
	return cpq
}

// Limit the number of records to be returned by this query.
func (cpq *CloudProviderQuery) Limit(limit int) *CloudProviderQuery {
	cpq.ctx.Limit = &limit
	return cpq
}

// Offset to start from.
func (cpq *CloudProviderQuery) Offset(offset int) *CloudProviderQuery {
	cpq.ctx.Offset = &offset
	return cpq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (cpq *CloudProviderQuery) Unique(unique bool) *CloudProviderQuery {
	cpq.ctx.Unique = &unique
	return cpq
}

// Order specifies how the records should be ordered.
func (cpq *CloudProviderQuery) Order(o ...cloudprovider.OrderOption) *CloudProviderQuery {
	cpq.order = append(cpq.order, o...)
	return cpq
}

// First returns the first CloudProvider entity from the query.
// Returns a *NotFoundError when no CloudProvider was found.
func (cpq *CloudProviderQuery) First(ctx context.Context) (*CloudProvider, error) {
	nodes, err := cpq.Limit(1).All(setContextOp(ctx, cpq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{cloudprovider.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (cpq *CloudProviderQuery) FirstX(ctx context.Context) *CloudProvider {
	node, err := cpq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first CloudProvider ID from the query.
// Returns a *NotFoundError when no CloudProvider ID was found.
func (cpq *CloudProviderQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = cpq.Limit(1).IDs(setContextOp(ctx, cpq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{cloudprovider.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (cpq *CloudProviderQuery) FirstIDX(ctx context.Context) int {
	id, err := cpq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single CloudProvider entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one CloudProvider entity is found.
// Returns a *NotFoundError when no CloudProvider entities are found.
func (cpq *CloudProviderQuery) Only(ctx context.Context) (*CloudProvider, error) {
	nodes, err := cpq.Limit(2).All(setContextOp(ctx, cpq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{cloudprovider.Label}
	default:
		return nil, &NotSingularError{cloudprovider.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (cpq *CloudProviderQuery) OnlyX(ctx context.Context) *CloudProvider {
	node, err := cpq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only CloudProvider ID in the query.
// Returns a *NotSingularError when more than one CloudProvider ID is found.
// Returns a *NotFoundError when no entities are found.
func (cpq *CloudProviderQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = cpq.Limit(2).IDs(setContextOp(ctx, cpq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{cloudprovider.Label}
	default:
		err = &NotSingularError{cloudprovider.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (cpq *CloudProviderQuery) OnlyIDX(ctx context.Context) int {
	id, err := cpq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of CloudProviders.
func (cpq *CloudProviderQuery) All(ctx context.Context) ([]*CloudProvider, error) {
	ctx = setContextOp(ctx, cpq.ctx, "All")
	if err := cpq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*CloudProvider, *CloudProviderQuery]()
	return withInterceptors[[]*CloudProvider](ctx, cpq, qr, cpq.inters)
}

// AllX is like All, but panics if an error occurs.
func (cpq *CloudProviderQuery) AllX(ctx context.Context) []*CloudProvider {
	nodes, err := cpq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of CloudProvider IDs.
func (cpq *CloudProviderQuery) IDs(ctx context.Context) (ids []int, err error) {
	if cpq.ctx.Unique == nil && cpq.path != nil {
		cpq.Unique(true)
	}
	ctx = setContextOp(ctx, cpq.ctx, "IDs")
	if err = cpq.Select(cloudprovider.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (cpq *CloudProviderQuery) IDsX(ctx context.Context) []int {
	ids, err := cpq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (cpq *CloudProviderQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, cpq.ctx, "Count")
	if err := cpq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, cpq, querierCount[*CloudProviderQuery](), cpq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (cpq *CloudProviderQuery) CountX(ctx context.Context) int {
	count, err := cpq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (cpq *CloudProviderQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, cpq.ctx, "Exist")
	switch _, err := cpq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (cpq *CloudProviderQuery) ExistX(ctx context.Context) bool {
	exist, err := cpq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CloudProviderQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (cpq *CloudProviderQuery) Clone() *CloudProviderQuery {
	if cpq == nil {
		return nil
	}
	return &CloudProviderQuery{
		config:     cpq.config,
		ctx:        cpq.ctx.Clone(),
		order:      append([]cloudprovider.OrderOption{}, cpq.order...),
		inters:     append([]Interceptor{}, cpq.inters...),
		predicates: append([]predicate.CloudProvider{}, cpq.predicates...),
		// clone intermediate query.
		sql:  cpq.sql.Clone(),
		path: cpq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Key string `json:"key,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.CloudProvider.Query().
//		GroupBy(cloudprovider.FieldKey).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (cpq *CloudProviderQuery) GroupBy(field string, fields ...string) *CloudProviderGroupBy {
	cpq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CloudProviderGroupBy{build: cpq}
	grbuild.flds = &cpq.ctx.Fields
	grbuild.label = cloudprovider.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Key string `json:"key,omitempty"`
//	}
//
//	client.CloudProvider.Query().
//		Select(cloudprovider.FieldKey).
//		Scan(ctx, &v)
func (cpq *CloudProviderQuery) Select(fields ...string) *CloudProviderSelect {
	cpq.ctx.Fields = append(cpq.ctx.Fields, fields...)
	sbuild := &CloudProviderSelect{CloudProviderQuery: cpq}
	sbuild.label = cloudprovider.Label
	sbuild.flds, sbuild.scan = &cpq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CloudProviderSelect configured with the given aggregations.
func (cpq *CloudProviderQuery) Aggregate(fns ...AggregateFunc) *CloudProviderSelect {
	return cpq.Select().Aggregate(fns...)
}

func (cpq *CloudProviderQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range cpq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, cpq); err != nil {
				return err
			}
		}
	}
	for _, f := range cpq.ctx.Fields {
		if !cloudprovider.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if cpq.path != nil {
		prev, err := cpq.path(ctx)
		if err != nil {
			return err
		}
		cpq.sql = prev
	}
	return nil
}

func (cpq *CloudProviderQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*CloudProvider, error) {
	var (
		nodes = []*CloudProvider{}
		_spec = cpq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*CloudProvider).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &CloudProvider{config: cpq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, cpq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (cpq *CloudProviderQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := cpq.querySpec()
	_spec.Node.Columns = cpq.ctx.Fields
	if len(cpq.ctx.Fields) > 0 {
		_spec.Unique = cpq.ctx.Unique != nil && *cpq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, cpq.driver, _spec)
}

func (cpq *CloudProviderQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(cloudprovider.Table, cloudprovider.Columns, sqlgraph.NewFieldSpec(cloudprovider.FieldID, field.TypeInt))
	_spec.From = cpq.sql
	if unique := cpq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if cpq.path != nil {
		_spec.Unique = true
	}
	if fields := cpq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, cloudprovider.FieldID)
		for i := range fields {
			if fields[i] != cloudprovider.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := cpq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := cpq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := cpq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := cpq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (cpq *CloudProviderQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(cpq.driver.Dialect())
	t1 := builder.Table(cloudprovider.Table)
	columns := cpq.ctx.Fields
	if len(columns) == 0 {
		columns = cloudprovider.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if cpq.sql != nil {
		selector = cpq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if cpq.ctx.Unique != nil && *cpq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range cpq.predicates {
		p(selector)
	}
	for _, p := range cpq.order {
		p(selector)
	}
	if offset := cpq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := cpq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// CloudProviderGroupBy is the group-by builder for CloudProvider entities.
type CloudProviderGroupBy struct {
	selector
	build *CloudProviderQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (cpgb *CloudProviderGroupBy) Aggregate(fns ...AggregateFunc) *CloudProviderGroupBy {
	cpgb.fns = append(cpgb.fns, fns...)
	return cpgb
}

// Scan applies the selector query and scans the result into the given value.
func (cpgb *CloudProviderGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cpgb.build.ctx, "GroupBy")
	if err := cpgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CloudProviderQuery, *CloudProviderGroupBy](ctx, cpgb.build, cpgb, cpgb.build.inters, v)
}

func (cpgb *CloudProviderGroupBy) sqlScan(ctx context.Context, root *CloudProviderQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(cpgb.fns))
	for _, fn := range cpgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*cpgb.flds)+len(cpgb.fns))
		for _, f := range *cpgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*cpgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cpgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CloudProviderSelect is the builder for selecting fields of CloudProvider entities.
type CloudProviderSelect struct {
	*CloudProviderQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (cps *CloudProviderSelect) Aggregate(fns ...AggregateFunc) *CloudProviderSelect {
	cps.fns = append(cps.fns, fns...)
	return cps
}

// Scan applies the selector query and scans the result into the given value.
func (cps *CloudProviderSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cps.ctx, "Select")
	if err := cps.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CloudProviderQuery, *CloudProviderSelect](ctx, cps.CloudProviderQuery, cps, cps.inters, v)
}

func (cps *CloudProviderSelect) sqlScan(ctx context.Context, root *CloudProviderQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(cps.fns))
	for _, fn := range cps.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*cps.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cps.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
