// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"kubecit/internal/biz"
	"kubecit/internal/conf"
	"kubecit/internal/data"
	"kubecit/internal/server"
	"kubecit/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo, logger)
	userRepo := data.NewUserRepo(dataData, logger)
	userUsecase := biz.NewUserUsecase(userRepo, logger)
	clusterRepo := data.NewClusterRepo(dataData, logger)
	k8sRepoGetter := data.NewK8sRepoGetter()
	clusterUsecase := biz.NewClusterUsecase(clusterRepo, k8sRepoGetter, logger)
	cloudHostRepo := data.NewCloudHostRepo(dataData, logger)
	cloudHostUsecase := biz.NewCloudHostUsecase(cloudHostRepo, logger)
	greeterService := service.NewGreeterService(greeterUsecase, userUsecase, clusterUsecase, cloudHostUsecase)
	grpcServer := server.NewGRPCServer(confServer, greeterService, logger)
	httpServer := server.NewHTTPServer(confServer, greeterService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
