// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Cluster is the predicate function for cluster builders.
type Cluster func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
